import CookieConsent from '@/components/CookiesConsent'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import type { Metadata } from 'next'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import { Bebas_Neue } from 'next/font/google'
import local from 'next/font/local'
import './globals.css'

const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bebas',
})

const avenir = local({
  src: [
    {
      path: '../../public/fonts/avenir_roman_12.otf',
      weight: '300',
    },
  ],
  variable: '--font-avenir',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = useMessages()
  return (
    <html lang={locale}>
      <body
        className={`${bebasNeue.variable} ${avenir.variable}`}
      >
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          {children}
          <CookieConsent />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
